<a href="https://colab.research.google.com/github/karelmastny/calculus1WithPython/blob/main/numpyLib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

numbers = [1,2,3,4,5]

np.mean(numbers)


3.0

In [5]:
x = np.linspace(1,7,5)
print(type(x))
x


<class 'numpy.ndarray'>


array([1. , 2.5, 4. , 5.5, 7. ])

In [6]:
numbers_np = np.array(numbers)
print(type(numbers))
print(type(numbers_np))

# some numpy functions work on both list and np array, some on np array only

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
numbers_np.min()

1

In [13]:
n = [ 4,3,2,6,7,1,8,5 ]
nn = np.array(n)
print(n)
n.sort()
print(n)

print(nn)
nn.sort()
print(nn)

[4, 3, 2, 6, 7, 1, 8, 5]
[1, 2, 3, 4, 5, 6, 7, 8]
[4 3 2 6 7 1 8 5]
[1 2 3 4 5 6 7 8]


In [14]:
# outplace / inplace operations

n = [ 4,3,2,6,7,1,8,5 ]
nn = np.array(n)
print(n)
n.sort()
print(n)

print(nn)
np.sort(nn)
print(nn)

[4, 3, 2, 6, 7, 1, 8, 5]
[1, 2, 3, 4, 5, 6, 7, 8]
[4 3 2 6 7 1 8 5]
[4 3 2 6 7 1 8 5]
